### PR TITLE
feat(config) use the host parameter and not a custom variable

### PR DESCRIPTION
**Pull request by kazuparis**
usage_example
Hello,

I actually tried this plugin and we are now using it.

We are actually working on a few hosts. We are using labels or group hosts. In the project, you used a custom variable. 
I think it's best to use :
env.getHost().getAddress()

Here the java doc description :

getHost
PluginEnvironment.Host getHost()
Returns the host configured for the Plugin. If multiple hosts are configured the Plugins execute method will be called repeatedly for each host. If the Plugin does not support hosts, this method will return null.
Returns:the configured host, or null if hosts are not supported
I made some quick test on my side and everything seems to be working well.

Please fill free to ask any change if anything seems buggy.

Thank you for your time.

Regards,

Sylvain Lebon

### CODE REVIEW

**Comment by centic9** [comment]
Thanks a lot for the suggestion and changes.

One thing I would like to do is to stay backwards-compatible with regards to the settings as many other users are using it with the current settings already. We should probably keep the URL-parameter in place and allow to enter either the URL or the protocol/port-host combination. 

E.g. take a look at https://github.com/Dynatrace/Dynatrace-Extended-EMail-Action-Plugin/blob/master/plugin.xml#L25 for how this can be done in the plugin.xml via a boolean parameter and depending properties.

**Comment by kazuparis** [comment]
I really think that using the native dynatrace host variable is more appropriate and reduce the monitoring configuration lines.
But off course I understand the compatibility need. Your suggestion seems to be simple. We will just have to think the unit test aspect. There is probably no need to test everything on both scenarios. We can maybe add a specific test validating that the boolean and the url mode switch is working.
Would that be ok ?

I may not be able to do that this week.

**Comment by centic9** [comment]
Yes, fine and no hurry!

**Comment by kazuparis** [comment]
Hi,
I made the changes. I will try it in Dynatrace next week and confirm that everything is working.
Sylvain

**Comment by kazuparis** [comment]
I confirm that everything is working as expected.

Regards,

Sylvain Lebon

**Comment by centic9** [comment]
Thanks a lot for the work, I have merged this now and will include this in the next release of the plugin.

**Comment by kazuparis** [comment]
No problem at all. I hope that this will be helpful.

**Pull request merged**
